---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/opendatahub-io/kserve/config/default?ref=master
  - network-policies.yaml

patches:
  - path: ./kserve-controller-manager-patch.yaml
  - path: ./inferenceservice-config-patch.yaml

configurations:
  - params.yaml
