---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../kserve-built
  - network-policies.yaml

patches:
  - path: ./kserve-controller-manager-patch.yaml
  - path: ./inferenceservice-config-patch.yaml

configurations:
  - params.yaml
